# Generated by Django 4.0.3 on 2022-04-20 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_reflection_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflection',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='PDPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('q2', models.CharField(choices=[('1', 'Never'), ('2', 'Occasionally'), ('3', 'Sometimes'), ('4', 'Often'), ('5', 'Always')], default='1', max_length=1)),
                ('q3', models.CharField(choices=[('1', 'Never'), ('2', 'Occasionally'), ('3', 'Sometimes'), ('4', 'Often'), ('5', 'Always')], default='1', max_length=1)),
                ('q4', models.CharField(choices=[('1', 'Never'), ('2', 'Occasionally'), ('3', 'Sometimes'), ('4', 'Often'), ('5', 'Always')], default='1', max_length=1)),
                ('q5', models.CharField(choices=[('1', 'Never'), ('2', 'Occasionally'), ('3', 'Sometimes'), ('4', 'Often'), ('5', 'Always')], default='1', max_length=1)),
                ('q6', models.CharField(choices=[('1', 'Never'), ('2', 'Occasionally'), ('3', 'Sometimes'), ('4', 'Often'), ('5', 'Always')], default='1', max_length=1)),
                ('q7', models.CharField(choices=[('1', 'Never'), ('2', 'Occasionally'), ('3', 'Sometimes'), ('4', 'Often'), ('5', 'Always')], default='1', max_length=1)),
                ('q8', models.CharField(choices=[('1', 'Never'), ('2', 'Occasionally'), ('3', 'Sometimes'), ('4', 'Often'), ('5', 'Always')], default='1', max_length=1)),
                ('q9', models.CharField(choices=[('1', 'Never'), ('2', 'Occasionally'), ('3', 'Sometimes'), ('4', 'Often'), ('5', 'Always')], default='1', max_length=1)),
                ('q10', models.CharField(choices=[('1', 'Never'), ('2', 'Occasionally'), ('3', 'Sometimes'), ('4', 'Often'), ('5', 'Always')], default='1', max_length=1)),
                ('q11', models.CharField(choices=[('1', 'Never'), ('2', 'Occasionally'), ('3', 'Sometimes'), ('4', 'Often'), ('5', 'Always')], default='1', max_length=1)),
                ('q12', models.CharField(choices=[('1', 'Never'), ('2', 'Occasionally'), ('3', 'Sometimes'), ('4', 'Often'), ('5', 'Always')], default='1', max_length=1)),
                ('q1', models.CharField(choices=[('1', 'Never'), ('2', 'Occasionally'), ('3', 'Sometimes'), ('4', 'Often'), ('5', 'Always')], default='1', max_length=1)),
                ('q13', models.CharField(choices=[('1', 'Never'), ('2', 'Occasionally'), ('3', 'Sometimes'), ('4', 'Often'), ('5', 'Always')], default='1', max_length=1)),
                ('q14', models.CharField(choices=[('1', 'Never'), ('2', 'Occasionally'), ('3', 'Sometimes'), ('4', 'Often'), ('5', 'Always')], default='1', max_length=1)),
                ('q15', models.CharField(choices=[('1', 'Never'), ('2', 'Occasionally'), ('3', 'Sometimes'), ('4', 'Often'), ('5', 'Always')], default='1', max_length=1)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
