# Generated by Django 4.0.3 on 2022-04-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_image_image_alter_pdpr_q1_alter_pdpr_q10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdpr',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pdpr',
            name='q1',
            field=models.IntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Often'), (5, 'Always')]),
        ),
        migrations.AlterField(
            model_name='pdpr',
            name='q10',
            field=models.IntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Often'), (5, 'Always')]),
        ),
        migrations.AlterField(
            model_name='pdpr',
            name='q11',
            field=models.IntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Often'), (5, 'Always')]),
        ),
        migrations.AlterField(
            model_name='pdpr',
            name='q12',
            field=models.IntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Often'), (5, 'Always')]),
        ),
        migrations.AlterField(
            model_name='pdpr',
            name='q13',
            field=models.IntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Often'), (5, 'Always')]),
        ),
        migrations.AlterField(
            model_name='pdpr',
            name='q14',
            field=models.IntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Often'), (5, 'Always')]),
        ),
        migrations.AlterField(
            model_name='pdpr',
            name='q15',
            field=models.IntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Often'), (5, 'Always')]),
        ),
        migrations.AlterField(
            model_name='pdpr',
            name='q2',
            field=models.IntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Often'), (5, 'Always')]),
        ),
        migrations.AlterField(
            model_name='pdpr',
            name='q3',
            field=models.IntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Often'), (5, 'Always')]),
        ),
        migrations.AlterField(
            model_name='pdpr',
            name='q4',
            field=models.IntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Often'), (5, 'Always')]),
        ),
        migrations.AlterField(
            model_name='pdpr',
            name='q5',
            field=models.IntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Often'), (5, 'Always')]),
        ),
        migrations.AlterField(
            model_name='pdpr',
            name='q6',
            field=models.IntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Often'), (5, 'Always')]),
        ),
        migrations.AlterField(
            model_name='pdpr',
            name='q7',
            field=models.IntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Often'), (5, 'Always')]),
        ),
        migrations.AlterField(
            model_name='pdpr',
            name='q8',
            field=models.IntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Often'), (5, 'Always')]),
        ),
        migrations.AlterField(
            model_name='pdpr',
            name='q9',
            field=models.IntegerField(choices=[(1, 'Never'), (2, 'Occasionally'), (3, 'Sometimes'), (4, 'Often'), (5, 'Always')]),
        ),
    ]
