# Generated by Django 4.0.3 on 2022-04-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_pdpr_total_alter_pdpr_q1_alter_pdpr_q10_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdpr',
            old_name='total',
            new_name='life_coping_total',
        ),
        migrations.AddField(
            model_name='pdpr',
            name='life_skills_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdpr',
            name='life_stress_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdpr',
            name='quality_of_life',
            field=models.IntegerField(default=0),
        ),
    ]
