# Generated by Django 4.0.3 on 2022-04-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_total_pdpr_life_coping_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflection',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
