# Generated by Django 4.0.3 on 2022-04-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_reflection_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflection',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
